### ISSUE TITLE
Multiple networks and static ipv4

### ISSUE THREAD

**Issue by Patazerty** [virt-lightning/virt-lightning#145]
First, let me thank a lot everyone for this handy tool. I am currently using it to run tests deployments of a k8s cluster and it really saves me a lot of time.

In my use case I need two network interfaces to simulate a 'public' network for apps and a 'private' one for k8s APIs. I also need static ipv4s for the private side of things. My `virt-lightning.yml` looks like  that:
```yaml
- name: whatever
  distro: debian-9
  networks:
    - network: virt-lightning
    - network: private
      ipv4: 10.1.1.10
[...]
```

`vl up` fails with the error "ipv4 already set!" as a network is already defined before the private one. Removing the `exit(1)` in `virt-lightning.py` allows the vms to boot up successfully (although without dhcp by default on the private interface but that's fine since the vm has connectivity with the first network).
I can/will work on a PR with a better approach than just commenting the `exit` call.
