### ISSUE TITLE
Support ovs bridge

### ISSUE THREAD

**Issue by jpic** [virt-lightning/virt-lightning#217]
Great software!!!

Can it support openvswitch bridge interfaces?

```xml
<interface type='bridge'>
 <mac address='52:54:00:71:b1:b6'/>
 <source bridge='ovsbr'/>
 <virtualport type='openvswitch'/>
 <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
</interface>
```

**Comment by goneri** [comment]
Hi @jpic!

Thank you. Yes, it sounds like a good idea. I imagine we need to add a new type of network. Something like:

```
networks:
  - network: virt-lightning
    nic_model: virtio
  - network: default
    nic_model: e1000
  - bridge: ovsbr
    mac: '52:54:00:71:b1:b6'
    virtualport_type: openvswitch
```
