### ISSUE TITLE
setting staitc ip with ivp4 dosen't work

### ISSUE THREAD

**Issue by proofy** [virt-lightning/virt-lightning#248]
Hi,
I have a problem to set a static IP address to VMs.
this is my virt-lightning.yaml:

```
- name: ansible
  distro: debian-11-genericcloud-amd64
  networks:
    - ipv4: 192.168.150.1
    - network: virt-lightning
- name: debian11
  distro: debian-11-genericcloud-amd64
  networks:
    - ipv4: 192.168.150.10
    - network: virt-lightning
- name: rocky
  distro: Rocky-8-GenericCloud.latest.x86_64
  ipv4: 192.168.150.20
- name: suse
  distro: openSUSE-Leap-15.3.x86_64-1.0.1-NoCloud-Build2.186
  networks:
    - ipv4: 192.168.150.30
- name: ubuntu
  distro: ubuntu-20.04
  ipv4: 192.168.150.40

```
With this I tried something to show you the problems:
This is the output in the console after vl up:

```
⚡ ansible 
⚡ debian11 
⚡ rocky 
⚡ suse 
⚡ ubuntu 
⌛ ok Waiting...
💻 ansible found at 192.168.150.1!
🛃 rocky QEMU agent found
🛃 suse QEMU agent found
💻 ubuntu found at 192.168.150.6!
💻 rocky found at 192.168.150.5!
💻 suse found at 192.168.150.30!
💻 debian11 found at 192.168.150.10!
👍 You are all set

```

problem 1:
in this example ansible  gets 192.168.150.1. But 1 is normally the IP of the host (same problem with vangrant, the reason I try your nice program here)
problem 2: 
setting IP like with ubuntu dosen't work. Would be enough to give an example in the documentation.
